trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: Bash@3
  displayName: 'Pushing Results to Quality Gate'
  inputs:
    targetType: 'inline'
    script: |
      docker pull ghcr.io/zaproxy/zaproxy:stable
      docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://www.example.com -g gen.conf -r testreport.html






